---
name: Form.Element.Resize
version: 0.01
author:
  - Edoardo Sabadelli <edoardo [at] sabadelli [dot] it>
abstract: A nice unobtrusive javascript class for add a mouse-driven feature to form fields
license: artistic
